localStorage
UsamaAhmadTs/GOOGLE-KEEP-ANGULAR pull request #1
Opened 2023-09-18 11:06 UTC by UsamaAhmadTs

2023-09-18 11:40 UTC, UsamaAhmadTs commented on src/app/components/navbar/navbar.component.scss
> +//}
Rizwan bhai i am changing px to rem/em in all css files
and add commented code in ToDo

2023-09-19 13:40 UTC, ts-rizwan requested changes

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/input/input.component.html
> +          <span class="material-icons-outlined hover small-icon">more_vert</span>
can you please check if we can make it more descriptive

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/input/input.component.ts
> +  text: string = '';
we should have the all the variable at the start of the component.

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/input/input.component.ts
> +  @Output() saveNote = new EventEmitter<{ title: string, text: string }>();
same as above we should have the @Input and @Output at the start of the component instead of in the middle of component

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/navbar/navbar.component.html
> +             srcset="./assets/images/user.jpg 1x, ./assets/images/user2x.jpg 2x " alt="user-pic">
why we use srcset here?

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/navbar/navbar.component.ts
> +  @ViewChild("form23zSaZ") form23zSaZ?: ElementRef<HTMLDivElement>
what is "form23zSaZ"?

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/notes/notes.component.html
> +      <span class="material-icons check-circle">check_circle</span>
can we remove underscore from check_circle?

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/notes/notes.component.html
> +              <span class="material-icons-outlined hover small-icon">more_vert</span>
same as above

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/notes/notes.component.scss
> +}
we need to replace all px to em/rem

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/sidenav/sidenav.component.html
> +          <div [style.display]="labelInput.value.length ? 'block' : 'none'" class="check-icon H"
is "H" is a class name? if yes I think it should be more descriptive and meaningful

2023-09-19 13:40 UTC, ts-rizwan commented on src/app/components/sidenav/sidenav.component.scss
> +//}
need to remove the commented code

2023-09-19 13:40 UTC, ts-rizwan commented on src/assets/scss/checkboxes.scss
> +//}
can you please take extra care when you committed commented code without a todo

2023-09-19 13:40 UTC, ts-rizwan commented on src/assets/scss/labels.scss
> +//}
same as above

2023-09-27 15:02 UTC, closed without merging